logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    br.com: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/sistema;DB_CLOSE_DELAY=-1
    username: sistema
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    contexts: dev, faker
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false

server:
  port: 8080

jhipster:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: ZWM0MTExZmNhZWEwMDQxMzVkNjc1MTQ4MjgwMmMxNzFkZGQzMjlmNjY0NmJlODljZjliMWU0MDMwZTI0MGU0MmM2OGI5ZWYxNzlhMDllNjMxYzI0OTk5ZjFmYmU5OWVmN2ZiYTdmNjBhZDZlYWQ4M2Y3YWE0MzVhMDk2NThjMDc=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  metrics:
    logs:
      enabled: false
      report-frequency: 60
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30
